### ISSUE TITLE
Polling components use `setInterval` rather than `setTimeout`

### ISSUE THREAD

**Issue by ticky** [buildkite/frontend#139]
On poorly-performing networks this could cause issues!

- [x] `app/components/agent/Show.js` (#235)
- [x] `app/components/agent/Index/installation.js` (#235)
- [x] `app/components/agent/Index/agents.js` (#158)

Noted by @keithpitt in #135
